version: "3.9"
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./son1k
    env_file: [./son1k/.env]
    ports: ["8000:8000"]
    depends_on: { redis: { condition: service_healthy } }
    volumes: ["./outputs:/outputs"]

  worker:
    build: ./son1k
    env_file: [./son1k/.env]
    command: bash -lc "celery -A src.celery_worker.celery_app worker --loglevel=INFO -Q ${CELERY_QUEUE_CPU:-cpu} --concurrency=${CELERY_WORKER_CONCURRENCY:-1}"
    depends_on: { redis: { condition: service_healthy } }
    volumes: ["./outputs:/outputs"]

  flower:
    image: mher/flower:latest
    env_file: [./son1k/.env]
    command: ["flower","--broker=${REDIS_BROKER_URL}", "--port=5555"]
    ports: ["5555:5555"]
    depends_on: { redis: { condition: service_healthy } }
